### ISSUE TITLE
Suggestion: Support IP2Location.io API

### ISSUE THREAD

**Issue by ip2location** [navinpeiris/geoip#57]
I would like to propose support for the IP2Location.io API. It has a free tier upon registration.

It is one of the fastest API available in the market right now.

**Comment by iloveitaly** [comment]
Great, I'd accept a PR for this!

**Comment by Liferenko** [comment]
Hello! 
the other day I connected geoip with IP2location.io. And I bet it was working smooth.
But now logs show this error
```
** (exit) an exception was raised:
* (ArgumentError) Unknown provider: ':ip2locationio'. Please check your geoip configuration.
(geoip 0.2.8) lib/geoip/lookup.ex:85: GeoIP.Lookup.lookup_url/2
(geoip 0.2.8) lib/geoip/lookup.ex:38: GeoIP.Lookup.get_from_provider/2
(geoip 0.2.8) lib/geoip/lookup.ex:23: GeoIP.Lookup.lookup/1
(* 0.1.0) lib/my_web/check_geolocation.ex:17: MyWeb.Plugs.CheckGeolocation.call/2
(* 0.1.0) MyWeb.Router.app/2
```

my configs are pretty straightforward:
```
#mix.exs
     {:geoip, "~> 0.2"}


#config/config.ex
config :geoip, provider: :ip2locationio, api_key: "63A**************2E*R*************4"
```

looks odd, because I clearly can see `:ip2locationio` as a provider in `lookup_url/2`.
Need to temporarily switch to `:ipinfo`

**Comment by ip2location-com** [comment]
Hi @Liferenko,

If you change the line in mix.exs to `{:geoip, git: "https://github.com/navinpeiris/geoip.git"}`, does the issue gone? We are able to run the plugin by using this config in dependency.

**Comment by wingchen** [comment]
I still got this, just FYI:

```
** (exit) an exception was raised:
    ** (ArgumentError) Unknown provider: ':ip2locationio'. Please check your geoip configuration.
        (geoip 0.2.7) lib/geoip/lookup.ex:86: GeoIP.Lookup.lookup_url/2
        (geoip 0.2.7) lib/geoip/lookup.ex:38: GeoIP.Lookup.get_from_provider/2
        (geoip 0.2.7) lib/geoip/lookup.ex:23: GeoIP.Lookup.lookup/1
```

**Comment by ip2location-com** [comment]
Hi @wingchen ,

Can you let us know the content of your mix.exs file? We would like to see if we can reproduce the same issue using the same content of the file.

**Comment by wingchen** [comment]
I was using the master branch from this repo:

```
      # geo
      {:geoip, git: "https://github.com/navinpeiris/geoip.git"},

```

I looked into the source code. I could not understand it either. `lookup.ex` looks fine from my perspective at: https://github.com/navinpeiris/geoip/blob/master/lib/geoip/lookup.ex#L84-L86

I just forked it out and I will play with it a bit.

**Comment by wingchen** [comment]
@ip2location my elixir 1.13.0 (I know it's old, we will update it soon) seems to like this style of functions better:
https://github.com/navinpeiris/geoip/commit/c30aed8ad6d9c942752b223964d4d839fe6df40e

do you want me to create a PR for it? I will update the rest of the providers too.

**Comment by ip2location-com** [comment]
Hi wingchen,

Sure, you can always create the PR, thanks for your effort!
